### ISSUE TITLE
name 'ConfigParser' is not defined

### ISSUE THREAD

**Issue by janainascal** [fabaff/mqtt-randompub#3]
Hi, i'm testing this project but couldn't make it work.

I have installed pip3 and intalled this project from there `pip3 install mqtt-randompub --user` and copy the file `https://github.com/fabaff/mqtt-randompub/blob/master/mqtt-randompub.example` to `resources/randompub.config`

But it hasn't load the configs, as shown in the erro below.
```
$ mqtt-randompub -f resources/randompub.config
Traceback (most recent call last):
  File "/home/jana/.local/bin/mqtt-randompub", line 8, in <module>
    sys.exit(main())
  File "/home/jana/.local/lib/python3.8/site-packages/mqtt_randompub/mqtt_randompub.py", line 128, in main
    args = opthandling.argparsing()
  File "/home/jana/.local/lib/python3.8/site-packages/mqtt_randompub/opthandling.py", line 24, in argparsing
    config = ConfigParser.SafeConfigParser()
NameError: name 'ConfigParser' is not defined

$ pip3 -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

I forget something?

**Comment by fabaff** [comment]
> I forget something?

No, `ConfigParser` was renamed.
